spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 681071438055-u58rnnddlv55251nrrgp5qehog3v23f5.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - profile
              - email
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8081/login/oauth2/code/google"
